### ISSUE TITLE
[1.12.2] [BUG] Failed /top over void causes server timeout crash

### ISSUE THREAD

**Issue by TheodoreHua** [ForgeEssentials/ForgeEssentials#2593] opened 2021-07-10 20:32 UTC
# WARNING:  Do not delete any of the sections below.  Improperly filled out issues will be closed if not rectified in a timely manner!

**Initial Steps**
- [X] I have updated to the latest build from [Jenkins](https://ci.forgeessentials.com/job/FE-1.12.2/) before reporting a bug
- [X] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [X] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log *(attached is modlist, although latest.log and debug.log are useless as it just shows the server crashing from a timeout, no relavent information)*.
- [X] Also, attached are the client logs (if applicable) **N/A**

**Describe the bug**
Failing (meaning there's nothing above the player to teleport to) a /top with nothing underneath (the void) causes the server to time out and crash.

Normally a failed on /top happens, FE teleports the player to the ground, it's likely that the timeout is happening because FE continuously searches for the ground when there's nothing to find (just the void).

**To Reproduce**
1. Go to the end or make a hole to the void
2. Make sure there is nothing above you
3. Make sure the only thing below you is the void
4. Jump off into the void and then attempt to use `/top` with nothing but the void below you and nothing above you
5. The server will time out

**Expected behavior**
/top to not work or something else happens rather than the server crashing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Initially Found On: 12.3.82 then double checked on (latest at time of writing): 12.3.110

**Additional context**
N/A

[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/6795904/modlist.txt)

**Comment by spacebuilder2020** [comment] 2021-07-12 22:55
I will investigate.

**Comment by spacebuilder2020** [comment] 2021-07-12 23:47
This is being caused by the code counting down until it finds a solid block.
https://github.com/ForgeEssentials/ForgeEssentials/blob/5a2ca8f51ec5c772ce4bb87f317b28b2136f6328/src/main/java/com/forgeessentials/teleport/CommandTop.java#L95

A fix will be added in a future build.

**Comment by spacebuilder2020** [comment] 2021-07-17 06:29
Fixed in 738d25d877b4e76f382e2be99952eba444512a1b

**Closed as completed by spacebuilder2020** 2021-07-17 06:29 UTC
Labels: bug, accepted
