### ISSUE TITLE
Crash FE

### ISSUE THREAD

**Issue by HeberonYT** [ForgeEssentials/ForgeEssentials#2112] opened 2016-07-13 16:58 UTC
Good day.
Here a common mistake that causes FE, mentions that the error report so here it is.
regards

http://pastebin.com/raw/5wZxGbzL

**Comment by spacebuilder2020** [comment] 2016-07-13 22:28
duplicate of https://github.com/ForgeEssentials/ForgeEssentials/issues/2066

**Closed** 2016-07-13 22:31 UTC
Labels: duplicate
