### ISSUE TITLE
Extra Utilities compatibility

### ISSUE THREAD

**Issue by HeberonYT** [ForgeEssentials/ForgeEssentials#2108] opened 2016-07-07 05:39 UTC
Hi.
I am using FE 1.7.10-1.4.4.1182 on my server with mods (forge 10.13.4.1558), but some crafteos mods are blocked, for example, unstable ingots and anything that requires them.
It does not work autonomus activator of Thermal Expansion.

I added the permissions to the group `_ALL_` but it seems not help.
`"fe.protection.craft.ExtraUtilities.unstableingot.*": "true",
"fe.protection.exist.ExtraUtilities.unstableingot.*": "true",
"fe.protection.inventory.ExtraUtilities.unstableingot.*": "true",
"fe.protection.use.ExtraUtilities.unstableingot.*": "true",`

Greetings.

**Comment by spacebuilder2020** [comment] 2016-07-14 20:07
Try turning /p debug
and recording what happens when you try to craft.  Also post your permissions.json file

**Comment by spacebuilder2020** [comment] 2016-07-21 14:57
@HeberonYT Did you solve your issue?

**Comment by FusionDesign** [comment] 2016-07-29 23:55
Our server has this issue as well. No command is logged when you go to grab the Unstable Ingots out of the vanilla crafting window. It will not allow you to pull out an unstable ingot using the normal Iron / Diamond recipe.

**Comment by spacebuilder2020** [comment] 2016-07-30 01:46
Can you give me more information about what mods you are using and what configs.   If you are using a modpack please include a sharecode.

**Comment by HeberonYT** [comment] 2016-07-30 05:53
@FusionDesign Sorry to hear that, I got tired of so many problems and limitations with this mod.
The solution was to delete, and move to kcauldron to use the essentials plugin which is great, no problem and also get better performance without this mod.
I leave a summary of everything that does not work.
1- The plots do not serve
2- Some recipes extra utilities are blocked
3- Some blocks do not work (activator autonomus)
4- Vip slots do not work
5- sudden Crash
6- Permission to deny colors and in chat format does not work.
7- not supported fastcraft
8- The graves do not keep all objects at death
9- Bad optimization, many checks, means low tps

**Comment by spacebuilder2020** [comment] 2016-07-30 07:34
Well, the main difference between forge essentials and bukkit essentials is bukkit essentials is far older and more mature.  Forge Essentials has been working hard to catch up but it is still far behind essentials.

**Comment by olee** [comment] 2016-07-31 22:16
@HeberonYT 
1. Nice to have a list of stuff that are the biggest show-stoppers for users
2. You are not forced to use every feature of FE :wink: 

As for those issues you mentioned:
1. Plots are still kinda under construction / half finished - there were not enough developers (1? 2?) to get this finished while at the same time taking care of the rest, too
2. see below
3. Probably a permission thing - there are generic permissions for fakeplayers which could block this
4. Should be checked as well - don't know if this ever had been reported
5. Well - if TF was installed on the server I can guess what happened - otherwise same thing - need crashlogs
6. same - needs to be reported + it helps to also remind us on issues that got inactive but are still imporant
7. rtfm - we have a proper guide on how to use fastcraft with FE together
8. From when was this? In there current version there shouldn't be any issue at all
9. FE has been optimized quite a lot - but what do you expect of the most powerful permission system for forge servers? Of course you will have a slight drop in TPS - though it can get serious if you do stuff like dropping 30+ quarries or something like that.

As for the unstable ingots: This is really a serious (and quite annoying) issue.
Even though I used Extra Utilities with FE on my own server as well (probably not hard to fix though) I heard this the first time.
It might be that it happens because I think extra utilities overwrites some of the recipe handler in MC which FE also does to handle crafting permissions.
Will need some investigation.

**Comment by ThePoet444** [comment] 2016-08-01 13:04
I just started a new server and have the same issue. Crafting the nuggets works fine. It's the unstable ingots with the iron that doesn't work.  The private server I'm running is basically the DW20 pack with every mod updated and a few others thrown in for fun.  A list of all the mods (even disabled ones) is here: [http://pastebin.com/gnVr8nAR](http://pastebin.com/gnVr8nAR)

**Comment by Techjar** [comment] 2016-08-11 12:21
Just tested and can confirm this also happens on my server.

**Comment by Techjar** [comment] 2016-08-11 12:43
So I got curious and looked into this. It's getting a stack trace and checking for a ContainerWorkbench at specific indices of the stack in it's recipe handler, so basically this can't be fixed from FE's side (unless you were to asm ExU).

**Comment by AnrDaemon** [comment] 2016-08-11 13:05
Test is without FE. I'd be surprised, if it would work.
There's many ways to break ExU ingots crafting, but there's a way to fix it as well.
Grab [this script](https://gist.github.com/AnrDaemon/ae34e020911d6fd822b92e4d16db115c) and include it into your MT blob.

**Comment by Techjar** [comment] 2016-08-11 13:08
Wouldn't this allow you to craft the ingots anywhere though, including by automated means?

**Comment by AnrDaemon** [comment] 2016-08-11 13:28
Try it? :) I didn't test it in autocrafters, though. Guess I'm too honest >.<

**Comment by olee** [comment] 2016-08-25 18:03
I tried crafting an unstable ingot in dev env and it worked without any problem.
@Techjar does it crash when trying to craft that ingot in prod or what exactly is wrong here?

**Comment by AnrDaemon** [comment] 2016-08-25 18:28
It doesn't crash.
The observed effect is the same as a desync between client and server recipe DB.
The crafted item appears in an output slot, but you can't retrieve it from there.
Happens when certain set of mods is present (the script I've linked above mentioning DragonAPI and/or Tinkers' Construct).

**Comment by Techjar** [comment] 2016-08-26 08:45
Yeah the problem is if anything inserts extra calls onto the stack in the crafting code path, it breaks, because like I said he's checking specific stack indices. It's not fixable from FE's side, needs to be fixed in ExU. He should be doing a class check on inventoryCrafting.eventHandler.

**Comment by olee** [comment] 2016-08-26 09:26
The weird thing is it worked for me!
I could easily pull the stacks out...

**Comment by Techjar** [comment] 2016-08-26 09:26
Try adding TiC?

**Comment by AnrDaemon** [comment] 2016-08-26 10:27
@Techjar can you cross-link the ExU side of the issue please?

**Comment by Techjar** [comment] 2016-08-26 12:17
I cannot as there it isn't actually open source.

**Comment by AnrDaemon** [comment] 2016-08-26 15:39
I mean, if there's an issue report on ExU side? If such thing ever exists.
Even closed-source projects often have public issue trackers.

**Comment by Zethalion** [comment] 2018-11-11 22:20
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response

**Closed** 2018-12-15 12:54 UTC
Labels: mod-compatibility, needs-verification
