### ISSUE TITLE
[Question] How to create a creative-only dimension in my survival world?

### ISSUE THREAD

**Issue by Telokis** [ForgeEssentials/ForgeEssentials#2239] opened 2017-03-31 18:08 UTC
I'd like to know how to create a creative dimension while all the other worlds are in survival.
The question can be splitted into two:

* How to toggle creative mode when going through the portal in one or another direction?
* How to save the survival inventory to restore it when the player comes back? (To prevent cheating)

**Comment by Zethalion** [comment] 2017-03-31 21:52
You need to do 2 things:
- assign a command on enter and exist of the zone the dimension is that puts the player into creative when entering and back to survival when leaving.
- set a value for fe.protection.inventorygroup for that zone.

However, the latter might or not function correctly. See https://github.com/ForgeEssentials/ForgeEssentials/issues/2228

**Comment by Telokis** [comment] 2017-03-31 22:11
With more investigation I noticed the `fe.protection.gamemode` value which can be used to toggle a gamemode in an area. However, it works pretty fine on an area inside a world but doesn't seem to work on a whole dimension:

* I am in survival, I go to the dimension --> Creative // OK
* I am go back to the original dimension --> Creative // Not OK

It only does so like this. If I am in creative before going, I am still in creative when I come back. Quite strange.

**Comment by Zethalion** [comment] 2017-04-17 20:41
Duplicate of #2228

**Closed by Zethalion** 2017-04-17 20:41 UTC
