### ISSUE TITLE
Feature Request: Polygon shaped Areas

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#1830] opened 2015-10-20 16:59 UTC
Polygon shaped Areas would be good for people who have non-cuboid shaped houses.

**Comment by liach** [comment] 2015-10-20 17:12
But it would make calculations much slower, since it really too time to calculate different shapes. But it would be a good idea that areas could be composed of different connected rectangle areas or just in circles, that would meet most people's requirement of polygons.

**Comment by olee** [comment] 2015-10-21 12:20
@liach You should leave those thoughts about computation to us :wink: 

@PitchBright yes, composed areas (areas consisting of multiple boxes, cylinders, etc) are also something I want to add.

However polygons are in fact quite a bit harder to calculate and especially defining them is also a problem. Do you think that it would be enough to combine multiple rectangular areas to the shape you need?

**Comment by PitchBright** [comment] 2015-10-21 13:52
Yep, totally... multiple rectangles would do the trick!

**Comment by Morketh** [comment] 2015-11-03 18:25
Well its kinda funny i was trying to do just this. using WorldEdit (packaged with FE) i was able to select a polygon but i think the lack of support may have caused this error when trying to WorldGuard it

Client Console:
```
[11:14:26] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
```
Server Console
```
[11:14:42] [Server thread/ERROR]: Couldn't process command: 'zone select CrossRoads'
java.lang.NullPointerException
        at com.sk89q.worldedit.regions.selector.Polygonal2DRegionSelector.selectSecondary(Polygonal2DRegionSelector.java:155) ~[Polygonal2DRegionSelector.class:?]
        at com.forgeessentials.compat.worldedit.WESelectionHandler.setEnd(WESelectionHandler.java:134) ~[WESelectionHandler.class:?]
        at com.forgeessentials.permissions.commands.CommandZone.parseSelect(CommandZone.java:291) ~[CommandZone.class:?]
        at com.forgeessentials.permissions.commands.CommandZone.parse(CommandZone.java:85) ~[CommandZone.class:?]
        at com.forgeessentials.core.commands.ParserCommandBase.func_71515_b(ParserCommandBase.java:20) ~[ParserCommandBase.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Not sure if this is informative on your research but it was something worth noting.

**Comment by olee** [comment] 2015-11-04 10:35
WorldEdit selection mode does not influence FE area shapes.
The error you get is probably a different bug that needs to be fixed.

**Comment by olee** [comment] 2015-11-05 10:26
This is actually a duplicate of #1747.
Closing this.

**Closed by olee** 2015-11-05 10:26 UTC
Labels: low-priority, request

**Comment by Morketh** [comment] 2015-11-07 08:01
in regards to the above Error it was due to trying to use the /zone select command
i First used World Edit to define a polygon and then
```
/zone define crossroads
```
 then trying to select the zone:
```
/zone select crossroads
```
gave that error
"[11:14:42] [Server thread/ERROR]: Couldn't process command: 'zone select CrossRoads'"
that is a ForgeEssentials command and not a world edit command is it not? im kind of confused how thats a world edit issue

**Comment by olee** [comment] 2015-11-07 09:39
@Morketh I know and I already fixed it.
The crash would have happened regardless how you defined the region.
The problem was that you were not in box-selection mode and FE wanted to set the WE selection to a box. This is fixed now and using `/area select <name>` will revert the selection mode to box.
