### ISSUE TITLE
[1710] [1330/1334] Forge Essentials crashes with at least Ars Magica 2

### ISSUE THREAD

**Issue by Hakker** [ForgeEssentials/ForgeEssentials#2206] opened 2016-12-27 20:45 UTC
http://pastebin.com/1Sbukr2m. 

That is the last part of the FML-server-latest log.
removing Forge Essentials loads everything fine.

**Comment by luacs1998** [comment] 2016-12-30 04:35
Try running arsmagica with sponge instead of FE and tell me if it still crashes.

It might be a mixin issue...

**Comment by liach** [comment] 2016-12-30 05:27
It is 1.7.10 which Sponge does not exist.

**Comment by Hakker** [comment] 2016-12-30 11:59
I just reverted back to build 1187 which does work

**Comment by luacs1998** [comment] 2016-12-30 12:49
Dupe of #2186

**Closed by luacs1998** 2016-12-30 12:49 UTC

**Comment by MalHT** [comment] 2017-07-21 16:04
I'm also having this issue (same `Tried to access DataManager before its initialization` error) with the latest build and found that build 1187 worked. Is there any information I can provide to help?

I notice this is closed as a duplicate but I'm not sure if the linked issue is actually related.
