### ISSUE TITLE
Area issue

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2045] opened 2016-03-23 23:43 UTC
Before one of the mods rudely closed my last issue before letting me reply I was saying. "I made an area that was very large and made an entry/exit message for it. I then made perms in it for disabling breaking and placing except by certain users. The perms work throught the area, but the entry and exit message appears throught it like if I move to another chunk in the area it will tell me I have left the area even though Im still in it and the perms are still working. I am not sure how or why it does this. Now please ask me for more info if you need rather than just say "You did it wrong" and closing my ticket. I have done it exactly right and since ive been using this mod since it was available and I have made plenty of zones and areas that are working just fine Im trying to find out if it has something to do with that chunk or region unloading as I went to Pos2. As I have said it is a really large area

**Comment by olee** [comment] 2016-03-24 00:07
Sorry if I offended you, but closing the other issue does not mean I won't provide any support.
It is just for devs as indication, that such an issue is (probably) not a bug and won't need any modification of the source code.
Please continue the conversation in #2044 - I will help you out until we can identify the problem.

**Closed by olee** 2016-03-24 00:07 UTC
