### ISSUE TITLE
Nether Portal 1.10.2 Newest Release

### ISSUE THREAD

**Issue by Euretyum** [ForgeEssentials/ForgeEssentials#2269] opened 2017-05-28 23:08 UTC
As stated by many others you can't go to the nether. The end works fine but the nether portal will light but won't let you travel. I just updated and deleted old files (all I know of) for the beta version for 1.10.2 and installed the new official release for 1.10.2 and can't seem to get the portal to work still. Would like to not have to reset any /homes or /spawn or any of my "guards" for spawn if at all possible.

**Comment by spacebuilder2020** [comment] 2017-05-28 23:32
Duplicate of #2236

**Closed as completed by spacebuilder2020** 2017-05-28 23:32 UTC
