### ISSUE TITLE
Crash when sending TPA request

### ISSUE THREAD

**Issue by Noobsloth** [ForgeEssentials/ForgeEssentials#1930] opened 2016-01-02 17:54 UTC
http://hastebin.com/azujolorex.1c

Was looking around at the latest version and found this issue.

**Comment by liach** [comment] 2016-01-02 18:06
To add a synchronization lock on the `Map<ICommandSender, QuestionData> questions` object?

**Comment by luacs1998** [comment] 2016-01-03 01:07
Dupe of #1820

**Closed by luacs1998** 2016-01-03 01:07 UTC
