### ISSUE TITLE
Twilight Forest - Item Permission Crash

### ISSUE THREAD

**Issue by xKillerbees** [ForgeEssentials/ForgeEssentials#1895] opened 2015-12-17 01:47 UTC
Description: (from user on server)
"I was using the Lamp of Cinders that i FINALLY found after 12hrs... to clear away the thorns to get to the inner castle but the server keeps chain crashing... i would assume it has something to do with me using the lamp on the thorns but im not 100% sure, it has happened... like 3-4 times so now im giving up until i get home from work tonight.​

Reproduce: Using Lamp of Cinders of Thorns to clear path to the castle in Twilight Forest​"

Crash: http://pastebin.com/G6ZCGP9v
Forge: forge-1.7.10-10.13.4.1558-1.7.10-universal.jar

Happened with 1041, updated to 1051 and it's still happening.

ItemPermissions {
# Enable the item permission manager
B:enabled=false
}

**Comment by liach** [comment] 2015-12-17 02:05
Add launch argument `-Dfe.safemode=true` could prevent this crash. TwilightForest is errorous.
Dupe of #1854

**Comment by xKillerbees** [comment] 2015-12-17 02:09
I turned on safemode in the main.cfg, thank you.

**Closed** 2015-12-17 05:04 UTC
