### ISSUE TITLE
There is no command to remove a group

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#2004] opened 2016-02-16 21:24 UTC
/p group <GROUP> create will create a group if it doesn't exist. There should be a similar command to remove a group. Maybe it can check to be sure it has no members. (/p group <GROUP> delete)

**Comment by UmFuZGFsbDIwMDA** [comment] 2016-02-17 21:33
I agree. I truly need this command.

**Comment by Zethalion** [comment] 2016-02-18 04:24
I think /p group [name] clear * should do it.

**Comment by ruphskunk** [comment] 2016-02-18 14:21
Zethalion, unfirtunately, all that does is remove the groups access to anything. It does not remove the group.

/p group testdelete create
Created group testdelete

/p group testdelete clear *
Cleared testdelete's access to * in zone _SERVER_

in permissions.json:
    "testdelete": {
      "fe.internal.group.priority": "20",
      "fe.internal.group": "true"
    }

**Comment by damonmensch** [comment] 2016-02-19 05:24
I guess for now the only way is to manually delete the group from the json file, at least until the command could be added.

**Comment by olee** [comment] 2016-02-22 11:12
I didn't add a group delete command for some reasons.
Group IDs can sometime be used in other modules as references.
Just deleting them could cause problems - also it would be horrible if you accidentally delete a group you wanted to keep and all permissions are gone.
This is why the only way to delete a groups is to delete by accessing the permission files right now.

But I think we can add a delete command with additional warnings and questioner verification now....

**Comment by Zethalion** [comment] 2018-11-11 22:57
Closing this as feature by design

**Closed by Zethalion** 2018-11-11 22:57 UTC
Labels: regression
