### ISSUE TITLE
How to disable a type of mob spawn all over the world

### ISSUE THREAD

**Issue by anamewing** [ForgeEssentials/ForgeEssentials#2035] opened 2016-03-18 18:33 UTC
I want to disable some creatures in every world from my server. 
I checked the issue #1178 , however, it's about protecting a zone.

I tried these two commands to prevent pig spawn:
```
/p global deny fe.protection.mobspawn.forced.Pig
/p global deny fe.protection.mobspawn.nature.Pig
```
It doesn't work. When I place a pig mobspawner, pigs are still spawned nearby.

I use `forge-1.7.10-10.13.4.1614-1.7.10-universal.jar` and `forgeessentials-1.7.10-1.4.4.1146-server.jar`.

**Comment by luacs1998** [comment] 2016-03-19 11:36
Dupe of #1990

**Closed by luacs1998** 2016-03-19 11:36 UTC

**Comment by anamewing** [comment] 2016-03-19 16:18
So, does the `fe.protection.mobspawn.nature` permission work properly?

**Comment by olee** [comment] 2016-03-22 12:55
Yes, but it's `fe.protection.mobspawn.natural.XYZ` not `fe.protection.mobspawn.nature.XYZ`!

**Comment by anamewing** [comment] 2016-03-22 13:27
@olee Thank you for finding out my mistake. Finally I can enjoy this game.
