### ISSUE TITLE
Request - Biome Specific Multiworld World Creation {Magical forest yay!} 

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1802] opened 2015-10-04 03:19 UTC
Basically I wish to make a biome specific multiworld. Can it be done? Please note I am running 1.7.10

**Comment by luacs1998** [comment] 2015-10-04 03:36
Dupe of #1163

**Closed by luacs1998** 2015-10-04 03:36 UTC

**Comment by Robijnvogel** [comment] 2015-10-12 10:37
It can already be done, but it will not be easy. The implementation in FE that these people are planning, will probably be way simpler, but if you do not want to wait you can try this:

1. Make sure you have the correct mods*
2. Generate a world. If you already have a world, you can skip this step.
3. Set up a world border with FE.
4 Pregen the world using FE (depending on the size of your world border, this may take hours to days to weeks. For me a 10000*10000 world took +-2,5 hours to generate.
5. Change the configs**
6. Restart the server.
7. Create a Multiworld default/overworld generation and whatever generator you wish to use.*
8. You can now repeat step 3 and 4 if you want and change back the configs after that.

*I myself use Alternate Terrain Generation (very configurable) and Biomes O' Plenty as generator types.
**To make a world (almost) completely exist out of Tainted Land:
ATG: You put Tainted Land in virtually every biome group and set the chance very high (100.0 for instance) or make sure that Tainted land is the only biome in each group.
Bop or Vanilla: In the Thaumcraft Config, set the weight of the Tainted Land Biome very high (100 for instance)

**Comment by olee** [comment] 2015-10-12 15:04
I can probably add one-biome world's quickly when I am back in 2 weeks.
