### ISSUE TITLE
Multiworld issues

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1751] opened 2015-09-12 08:50 UTC
Merging all those multiworld issues here.
Please do not post further issues until I got time to fix the current system.
- [ ] #1831
- [ ] #1804 
- [ ] #1769 
- [ ] #1722
- [ ] #1697
- [ ] #1613
- [ ] #1597
- [ ] Feature requests go here: #1163

**Comment by krakel** [comment] 2015-11-21 19:08
Sorry for my impatience, what is your timeline for this issues? You know, the multiworld part ist the base of our modpack Shattered World.

**Comment by DomAmato** [comment] 2016-01-19 07:03
I am having the same problem as https://github.com/ForgeEssentials/ForgeEssentials/issues/1831
this is with 1.8 which I know development is moving towards 1.8.9 but has there been any progress made on this? Until it is I am stuck on 1.7.10. I would be interested in helping out if there is a helpful direction to point me in

**Comment by olee** [comment] 2016-01-21 20:08
Okayyy.... I really should go take care of multiworld...
I will try to get some things done this weekend.

**Comment by DomAmato** [comment] 2016-02-20 21:51
is there a workaround? in https://github.com/ForgeEssentials/ForgeEssentials/issues/1993 you mention the bug can be alleviated with a chunk loader

**Comment by olee** [comment] 2016-02-22 11:34
Yes - try placing a small chunkloader in a multiworld directly after creating and getting teleported to it.
That (might) help to prevent the bug.

**Comment by DomAmato** [comment] 2016-02-24 01:12
I still get the ticking world error on startup

```
// Uh... Did I do that?

Time: 2/23/16 6:03 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)
```

For a chunk loader I took this - http://www.curse.com/mc-mods/minecraft/chunkloader-simple and made a 1.8 version, https://github.com/Digital-Youth-Network/Items/blob/1.8/com/dyn/item/blocks/BlockChunkLoader.java

**Comment by DomAmato** [comment] 2016-02-27 03:10
I managed to make it stop crashing, it wasn't a chunk loading issue it was a null pointer caused by a never initialized villageCollection during the world creation. I don't know why this is the case as the decompiled code for forge does initialize a villageCollection in the init() function


    public class WorldServer...

    public World init()
    {
        this.mapStorage = new MapStorage(this.saveHandler);
        String s = VillageCollection.func_176062_a(this.provider);
        VillageCollection villagecollection = (VillageCollection)this.perWorldStorage.loadData(VillageCollection.class, s);

        if (villagecollection == null)
        {
            this.villageCollectionObj = new VillageCollection(this);
            this.perWorldStorage.setData(s, this.villageCollectionObj);
        }
        else
        {
            this.villageCollectionObj = villagecollection;
            this.villageCollectionObj.func_82566_a(this);
        }
        ....

I added this line at line 270
worldServer.villageCollectionObj = new VillageCollection(worldServer);
in MultiworldManager and it no longer crashes when I create a world

```
public class MultiworldManager ....

// Create WorldServer with settings
            WorldServer worldServer = new WorldServerMultiworld(mcServer, savehandler, overworld.getWorldInfo(), //
                    world.dimensionId, overworld, mcServer.theProfiler, world);
            // Overwrite dimensionId because WorldProviderEnd for example just hardcodes the dimId
            worldServer.provider.setDimension(world.dimensionId);
            worldServer.villageCollectionObj = new VillageCollection(worldServer);
            worldServer.addWorldAccess(new WorldManager(mcServer, worldServer));


```

I will keep investigating to see if there is anything else related to the crashes

**Comment by DomAmato** [comment] 2016-02-27 05:39
Now that it doesn't crash I also notice that the new worlds are just clones of the old one and setting the arguments otherwise has no effect

**Comment by DomAmato** [comment] 2016-02-27 08:08
This fixes the new world generation though they all have a nether portal at the center

```
    // Create WorldServer with settings
    WorldSettings settings = new WorldSettings(world.seed, mcServer.getGameType(), mcServer.canStructuresSpawn(), mcServer.isHardcore(), WorldType.parseWorldType(world.worldType));
    WorldInfo info = new WorldInfo(settings, world.name);

    WorldServer worldServer = new WorldServerMultiworld(mcServer, savehandler, info, world.dimensionId, overworld, mcServer.theProfiler, world);
    // Overwrite dimensionId because WorldProviderEnd for example just hardcodes the dimId
    worldServer.provider.setDimension(world.dimensionId);
    worldServer.init();
```

**Comment by DomAmato** [comment] 2016-07-29 00:09
@spacebuilder2020 The fix I mention above has been working for me for 1.8 and 1.8.9. Hopefully that makes your life easier

**Comment by spacebuilder2020** [comment] 2016-07-29 00:53
Ok

I plan to try it

**Comment by olee** [comment] 2016-07-31 22:20
Well let me warn you - MC world initialization is a really weird fu**ed up stuff.
I'm not sure if that fix will work all the time. :sweat_smile: 
Especially manually calling init could cause problems - who knows...
Go ahead and test it

**Comment by spacebuilder2020** [comment] 2016-07-31 22:30
good point.  I have been too busy in real life to look at any of this this week.  But I will try to find some time to start playing around with all of this stuff.

**Closed** 2016-08-28 19:23 UTC
Labels: accepted, bug, high-priority

**Comment by olee** [comment] 2016-08-28 19:26
FINALLY!
Multiworlds now properly unload and reload when needed.
This should fix nearly all issues with that module and finally allow adding some proper features like individual worldgen to it.
