### ISSUE TITLE
Bug - Permmission tables out of whack "Again"

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1829] opened 2015-10-19 20:14 UTC
So I am going to go ahead and zip all the information I have based on "FE" and "Logs" its gonna be a pain but maybe this will help the team as I don't understand how the permissions are handled and I don't know what folder the file that controls said permissions is located so I just gathered all files including logs. The corruption seems to have occurred in the last 48 hours. I am using fe most recent beta ending in 1008.

https://www.dropbox.com/s/pa9q3az9cd6ivte/FE-Permission-Corruptions.zip?dl=1

**Comment by olee** [comment] 2015-10-20 01:27
You should also tell us WHAT is not working.
Just telling us you have problems with permissions, does not really help.

**Comment by DPxKnightxZero** [comment] 2015-10-20 19:27
Okay so that is not something I am capable of doing because the effects seems randomized ... I kid you not one time people no longer took breathing damage another time we could no longer open chests. A time before that everyone had god mode and creative and monsters wouldn't die; this is exactly what I mean by permissions out of whack. You need to study these logs because I believe somewhere there is a key. I would do it myself but I have absolutely know way to understand what anomaly I would be looking for.

**Comment by DPxKnightxZero** [comment] 2015-10-27 02:36
The only information I can give you is it has to do with "/plot" It seems to occur after we attempted to not have mobs spawn in plots and zones.

**Comment by olee** [comment] 2015-10-27 09:45
What occurs?
Give me a manual to reproduce it!
And if you can't reproduce it, it *could* also be an error you made yourself (though not necessarily).

**Comment by DPxKnightxZero** [comment] 2015-10-27 12:14
Okay that is the thing the information I have provided is seriously all I have because the second time it happened I was not present and before it occurred one of my admins was working on zoning for setting up defense for a shop. 

Could you implement a log keeper for plot commands etc? I can help debug more effectively if we could gather a great deal more info during game play.

**Comment by olee** [comment] 2015-10-27 14:27
You can enable logging of commands in FE (main.cfg).

**Comment by DPxKnightxZero** [comment] 2015-10-27 23:48
Alright thank you I will do that so I can help you figure out what the exact cause of things are.

**Comment by DPxKnightxZero** [comment] 2015-10-28 03:35
I finally have some information!!!

Forge Essentials Java Hibernation Crash and Corruption? 
https://gist.github.com/DPxKnightxZero/106f59502ef88fe5e20a

**Comment by olee** [comment] 2015-12-25 12:53
I guess we can close this....

**Closed by olee** 2015-12-25 12:53 UTC
Labels: needs-verification
