### ISSUE TITLE
Request - Faction Support

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1770] opened 2015-09-21 14:07 UTC
So I have had close to about 12 people in the last 3 days ask me if our sever is a faction server and so I have to ask it was possible for the essentials team to add a module with such support. I know I request a lot so please take your time also this would be less of a priority than land claim. Here is an example of the affects I am looking to add.

http://www.planetminecraft.com/blog/how-to-make-a-successful-factionpvp-server/

**Comment by luacs1998** [comment] 2015-09-21 14:53
Duplicate of #1345 

@olee before you go thumbing for a month could you please get this done? :D

**Closed by luacs1998** 2015-09-21 14:53 UTC

**Comment by olee** [comment] 2015-09-21 16:58
Hm... you expect to finish me a possibly extremely complicated feature in that short time while I'm also busy with preparations for the trip?

Nothing easier than that :smile:

**Comment by DPxKnightxZero** [comment] 2015-09-21 17:15
@olee Lol XD

**Comment by olee** [comment] 2015-09-21 17:28
(OT - as this post is irrelevant anyway considering there is # 1345)
How come you post here soo often but aren't on IRC with us? :smirk:

**Comment by DPxKnightxZero** [comment] 2015-09-21 20:31
Because my brain keeps forgetting you have an irc ... also I already forgot the info ... tell you what give me the info etc one last time and I will book mark all of it promise.
