### ISSUE TITLE
Economy.cfg

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2056] opened 2016-03-31 01:21 UTC
I have copy and pasted my prices in my Economy config for item, but it doesnt seem to be working properly. Is there an example file I can see so I can make sure the formatting is correct?

**Comment by MickScandalous** [comment] 2016-03-31 01:25
Ive added my file to see if anything is wrong
[Economy.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/196846/Economy.zip)

**Comment by MickScandalous** [comment] 2016-03-31 02:35
Also is there any way to set these prices in-game?

my Forge Essentials Version is: forgeessentials-1.7.10-1.4.4.1146-server (1)

**Comment by spacebuilder2020** [comment] 2016-05-07 04:40
I think you use permissions, however I am not sure what node to use.  For setting start budget you use
"p global value fe.economy.startbudget 500", so you might use something similar for item prices.

I am going to take a look at the source code and get back to you on that.

**Comment by MickScandalous** [comment] 2016-05-17 16:16
yes, I appreciate you looking into it, AlsoI am not running fast craft so no worries there

**Comment by spacebuilder2020** [comment] 2016-05-17 16:32
np

**Comment by olee** [comment] 2016-08-26 13:39
@MickScandalous I cannot find any direct problem with the config file you posted.
This should normally make items have the prices you set after server restart or `/feinfo reload`.

Also `/sellprice` is a command which makes FE guess prices for crafted items based on the prices for the resources put into the crafted item. It can also be used to set prices directly with `/sellprice set <item> <price>`. These prices (same as calculated ones) are **only** stored in `./ForgeEssentials/Prices.txt` which looks the same as Economy.cfg. You can then copy this file over Economy.cfg to apply the changes (also `/sellprice save` does this automatically).

**Comment by spacebuilder2020** [comment] 2018-11-02 05:11
@MickScandalous If we do not receive a response from you in a week, this issue will be closed as part of an effort to clean up stale issues.

**Comment by MickScandalous** [comment] 2018-11-02 12:10
@spacebuilder2020 I havnt recieved a response from you in 2 years lol

**Comment by spacebuilder2020** [comment] 2018-11-03 03:45
lol...  If you had resolved your issue you should have responded to olee's comment ages ago.  At this point, the issue is so old that the fire has gone cold ages ago, so I am just going to close this issue.

**Closed by spacebuilder2020** 2018-11-03 03:45 UTC
Labels: bug, needs-verification

**Comment by MickScandalous** [comment] 2018-11-03 23:18
if you actually read his post you would see he didnt actually resolve the issue....your mod died when MS bought this game anyways.
