### ISSUE TITLE
Branch Version Release Request - 1.8.9

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1944] opened 2016-01-12 01:14 UTC
So everyone suddenly started updating all their mods to 1.8.9 is it possible to start a branch? I am more than happy to spend hours testing it. Also I donated a $1.92 sorry it was not more. I wish I could give you way more. :D

**Comment by luacs1998** [comment] 2016-01-12 04:40
Dupe of #1141.

Thanks for the donation, though - we really appreciate it.

**Closed by luacs1998** 2016-01-12 04:40 UTC

**Comment by TerdyTheTerd** [comment] 2016-01-12 11:49
Speaking of donations, there should be a donator wall :p
