### ISSUE TITLE
can not craft anything on my Server with FE!

### ISSUE THREAD

**Issue by MSandro** [ForgeEssentials/ForgeEssentials#2307] opened 2017-07-31 19:41 UTC
Hi I installed ForgeEssentials to my FTB Beyond server and since this, I can not craft anything on the server... :(
Why is this happening??? I don't changed the ForgeEssentials configurations at all.
No log will displayed on the Server and the Client.

Please help.

Minecraft: 1.10.2
Forge: 2422
ForgeEssentials: 10.3.1375
WorldEdit: 6.1.4-dist

**Comment by Zethalion** [comment] 2017-07-31 22:32
Duplicate of https://github.com/ForgeEssentials/ForgeEssentials/issues/2300

**Closed as completed by Zethalion** 2017-07-31 22:32 UTC
