### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentials#1430] opened 2015-04-21 14:28 UTC
I suggest a localization for the language files of the server, because, for exemple, not everyone speacks english. My server is Portuguse, and translating the texts will be really helpful.

I think this is a workable task, but, its necessary

NOTA: Just the texts in game

**Comment by luacs1998** [comment] 2015-04-21 14:35
Dupe of #1389

**Comment by liach** [comment] 2015-04-21 14:35
Yes FE should use .lang. But...

**Comment by luacs1998** [comment] 2015-04-21 14:37
A second problem I did not mention in #1389 was that once you set a locale, it applies to the *entire server*.

Meaning, if my server is Mandarin and I have a French guy log in, he gets Mandarin text, AND no option to change it. In such a case, localization does him a fat load of good.

**Comment by luacs1998** [comment] 2015-04-21 15:02
@liach .lang or .xml it makes no difference. I still need to come up with a parser for the files. And I still need to figure out where to read the files from. And I still need to write the file itself. And I still need to come up with a way to package the locales...

It's not as easy as you guys think it is. Also, I don't think we'd be able to maintain any other locales besides en_US and de_DE...

**Comment by olee** [comment] 2015-04-21 15:28
I am writing a small translator which will be easy to integrate.
The idea is to replace all calls of 
`String.format("Some message with arg = %s", args)` with our own 
`Translator.format("Some message with arg = %s", args)`.
This method would manage a map of all found orgininal, english messages and on server shutdown saves this as a properties file that would look like this:
````
Some message with arg \= %s=
Player %s has been teleported to %s=
Player %s has been healed=
````

Then server owners can modify this file **themselves** if they want to to provide some translations.
And if they are nice, they will share these with us so we can update (easy with diff tool) our hosted translation files.
````
Some message with arg \= %s=Irgendeine Meldung mit Argument \= %s
Player %s has been teleported to %s=Spieler %s wurde nach %s teleportiert
Player %s has been healed=Spieler %s wurde geheilt
````

**Comment by evernife** [comment] 2015-04-21 15:48
Excellent idea :D

**Comment by olee** [comment] 2015-04-21 22:23
Well part of it is done now.
However there are a lof of messages in FE that are not covered by the new translator yet.

**Comment by liach** [comment] 2015-04-21 22:25
So it'll be a command for changing localization or get it from client?

**Comment by liach** [comment] 2015-04-21 22:25
So it'll be a command for changing localization or get it from client?

**Comment by olee** [comment] 2015-04-21 22:36
There is no way to change if for the client only, because FE is a server mod.

**Comment by olee** [comment] 2015-04-22 13:06
Some more translations in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/1f3d58560f9e678b77125d3f36cf56f7eeaaffce

**Comment by luacs1998** [comment] 2015-09-29 15:39
I'll just close this in the meantime then.

**Closed by luacs1998** 2015-09-29 15:39 UTC
Labels: request

**Comment by aschmois** [comment] 2015-09-29 15:51
This seems easy enough for a wide range regex refactor, I'll give it a try in a few minutes.

**Comment by liach** [comment] 2015-09-29 15:56
How about putting sample loc files in the felocalization? Which should download on user's own.

**Comment by aschmois** [comment] 2015-09-29 15:59
The server, without some major backing, cannot send localized messages to each user. Because the server sends broadcast messages to its users. I can finish localizing all format strings though. But that will be a server wide localization.

**Comment by olee** [comment] 2015-09-29 16:03
FE currently only supports server wide translations with the automatically generated mapping file.
It is possible to slightly change the framework so that it can translate message based on user preferences.
However this is a lot of work and we won't do that with the current amount of team members.

**Comment by liach** [comment] 2015-09-29 17:08
So I guess it would be better if we add more hooks on the client, like specialized localization, secured password on client, and some rendering functions.

**Comment by olee** [comment] 2015-09-29 17:26
No - localization only available with client mod is not feasible.
The only thing we could add is that the client mod tells the server the language of the client.

**Comment by liach** [comment] 2015-12-18 05:48
@olee How about getting client information in `C15PacketClientSettings`?

**Comment by aschmois** [comment] 2015-12-18 05:55
The problem isn't knowing whether or not the client can send language info. It's the fact that the server doesn't send a message to each individual client. It sends a broadcast message. Making this happen would require a complete rewrite of the server client communication.

**Comment by olee** [comment] 2015-12-22 13:44
It's just as @aschmois said.
Global localiation is possible now and that should be enough - hopefully.
