### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Xodetaetl** [ForgeEssentials/ForgeEssentials#1950] opened 2016-01-15 00:47 UTC
Doing some development myself, I know how much writing docs is boring but it's essential and cannot be done by someone other than the developper(s) who know the code very well.

Looking at the wiki, at Commands.cfg and main.cfg, there are many undocumented commands and modules and outdated parts for the rest.

**Comment by luacs1998** [comment] 2016-01-15 07:44
Duplicate of #1529

**Closed by luacs1998** 2016-01-15 07:44 UTC
Labels: wiki
