### ISSUE TITLE
Items are falling from the sky on death

### ISSUE THREAD

**Issue by AngryBenko** [ForgeEssentials/ForgeEssentials#2285] opened 2017-06-28 22:41 UTC
I'm running on forgeessentials-1.10.2-10.2.1365-server.jar. When I die, my items do not drop on the ground, but they fall from the sky a couple of seconds later. On a related note, whenever I disable fly, my character teleports to the highest height and begins to fall back to the ground, regardless of my height when I disabled fly.

**Comment by spacebuilder2020** [comment] 2017-06-30 00:44
duplicate of #2284

**Closed as completed by spacebuilder2020** 2017-06-30 00:44 UTC
