### ISSUE TITLE
Suppress FakePlayer death messages

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1833] opened 2015-10-25 15:55 UTC
used version: 1.4.3.1008-nightly
hey guys!
we are getting some more death messages from mob farms like
... was slain by [EioKillera]
Mighty Skeleton was slain by [Minecraft]
is there a feature to disable messages completely OR can you fix this messages produced by non players entities eg machines ?

greetings

-jogi

**Comment by olee** [comment] 2015-10-26 15:28
We could think about it....

But on the other side, messages like *"... was slain by [EioKillera]"* should be there so you actually know who died :confused:

**Comment by DPxKnightxZero** [comment] 2015-10-27 02:35
It is pretty spammy.

**Comment by olee** [comment] 2015-10-27 09:47
How many times die players through FakePlayers?
I never even had that happen to myself .... I wouldn't even know how to do it....

**Comment by DPxKnightxZero** [comment] 2015-10-27 12:11
Um ... well with headcrumbs and hates ... about 7 fake players can die every 5 mins.

**Comment by Entoarox** [comment] 2015-10-29 13:11
Do you have Cofh Core installed? Cause that causes death messages to show up for any named non-player entities that die, and there is a config option to disable that.

**Comment by DPxKnightxZero** [comment] 2015-10-29 21:57
Thank you @Entoarox I will look into it.

**Comment by luacs1998** [comment] 2015-11-01 04:50
@DPxKnightxZero does changing the cofh core settings work? Can I close this?

**Comment by DPxKnightxZero** [comment] 2015-11-02 12:36
No it failed.

**Comment by spannerman79** [comment] 2015-11-15 05:27
Perhaps move this notification into a permission node?

For example `fe.chat.notification.death` default: true so if you want it negated just add `-fe.chat.notification.death` to user/group

**Comment by olee** [comment] 2015-11-15 10:13
The problem is that these death messages are not from FE, but from MC itself...
But we can think about it.

@luacs1998 could you take a look into where the messages are generated?

**Comment by luacs1998** [comment] 2015-11-20 00:50
I've found it.

Forge should have added a check for players but I assume it didn't.

Not really sure if it's our place to fix stupidity, though.

**Comment by spannerman79** [comment] 2015-11-20 04:46
Personally I find it amusing to see those messages but if it really bothered you @DPxKnightxZero & @jogi01 open an issue over at the forge issue tracker or post on the forge forums.

This is something that I think forge dev team needs to look at, address or dismiss

**Comment by olee** [comment] 2015-11-20 08:51
Exactly.
FE *could* do this, but FE is not really the right place to do this...

**Comment by luacs1998** [comment] 2015-11-22 01:21
Should I close this?

**Comment by spannerman79** [comment] 2015-11-23 05:01
@luacs1998 I think this issue should be closed, this is not a specific FE issue but needs to be resolved from Forge dev team themselves if/when they decide to

**Closed** 2015-11-23 11:14 UTC
Labels: low-priority, needshook, request
